package main

import (
	"bytes"
	"encoding/json"
	"go/format"
	"log"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/vorlif/spreak/internal/cldrplural/ast"
)

var pluralsFile = filepath.FromSlash(filepath.Join("./plurals.json"))

func main() {
	data, err := os.ReadFile(pluralsFile)
	checkError(err)

	root := &PluralsFile{}
	checkError(json.Unmarshal(data, root))

	dataSets := make(map[string]*DataSet, 40)
	for lang, jsonRules := range root.Supplemental.PluralsTypeCardinal {
		h := jsonRules.hash()
		if _, ok := dataSets[h]; ok {
			dataSets[h].Languages = append(dataSets[h].Languages, lang)
			continue
		}

		dataSets[h] = &DataSet{
			Languages: []string{lang},
			Rules:     jsonRules.ToData(),
		}
	}

	executeAndSafe("../builtin_gen.go", codeTemplate, dataSets)
	executeAndSafe("../builtin_gen_test.go", testTemplate, dataSets)
	executeAndSafe("../evaluation_gen_test.go", evaluationTest, dataSets)
}

// executeAndSafe applies the DataSet's to a parsed template and saves the result correctly
// formatted in a file 'name'.
func executeAndSafe(name string, tmpl *template.Template, dataSets map[string]*DataSet) {
	var buf bytes.Buffer
	err := tmpl.Execute(&buf, dataSets)
	checkError(err)

	p, err := format.Source(buf.Bytes())
	checkError(err)

	file, err := os.OpenFile(name, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0644)
	checkError(err)
	defer file.Close()

	_, err = file.Write(p)
	checkError(err)
}

func checkError(err error) {
	if err != nil {
		log.Fatalf("Error: %s\n", err)
	}
}

var templateFuncs template.FuncMap = map[string]interface{}{
	"ConvertToGo": func(rawRule string) string {
		rule, err := ast.Parse(rawRule)
		checkError(err)
		return compileNode(rule.Root)
	},
	"ExtractSamples": func(rawRule string) []string {
		rule, err := ast.Parse(rawRule)
		checkError(err)
		return rule.Samples
	},
	"HasCondition": func(rawRule string) bool {
		return !strings.HasPrefix(strings.TrimSpace(rawRule), "@")
	},
}

var codeTemplate = template.Must(template.New("rule").Funcs(templateFuncs).Parse(`// This file is generated by cldrplural/generator/generate.sh; DO NOT EDIT
package cldrplural

import "math"

func init() {
{{range $key, $data := .}}
	addRuleSet({{printf "%#v" $data.Languages}}, &RuleSet{
		Categories: newCategories({{range $i, $cat := $data.Categories}}{{if $i}}, {{end}}{{$cat}}{{end}}),
		FormFunc: func(ops *Operands) Category { 
			{{range $data.Rules}}
				{{if HasCondition .Raw}}
					// {{.WithoutExamples}}
					if {{ConvertToGo .Raw}} {
						return {{.Category}}
					}
				{{else}}
					{{if .WithoutExamples}}// {{.WithoutExamples}}{{end}}
					return {{.Category}}
				{{- end -}}
			{{end}}
		},
	})
{{end}}
}
`))

var testTemplate = template.Must(template.New("rule").Funcs(templateFuncs).Parse(`// This file is generated by cldrplural/generator/generate.sh; DO NOT EDIT
package cldrplural

import (
	"testing"

	"golang.org/x/text/language"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

{{range $key, $data := .}}
func TestPrebuild{{$data.Name}}(t *testing.T) {
	for _, lang := range {{printf "%#v" $data.Languages}} {
		set, found := prebuildRuleSets[language.MustParse(lang)]
		require.True(t, found)
		{{range $data.Rules}}
			{{$samples := ExtractSamples .Raw}}
			for _, sample := range {{printf "%#v" $samples}} {
				op := NewOperands(sample)
				assert.Equal(t, {{.Category}}, set.FormFunc(op)) 
			}
		{{end}}
	}
}
{{end}}
`))

var evaluationTest = template.Must(template.New("rule").Funcs(templateFuncs).Parse(`// This file is generated by cldrplural/generator/generate.sh; DO NOT EDIT
package cldrplural

import (
	"testing"

	"github.com/stretchr/testify/assert"

	"github.com/vorlif/spreak/internal/cldrplural/ast"
)

{{range $key, $data := .}}
func TestEvaluate{{$data.Name}}(t *testing.T) {
	var rule *ast.Rule
	{{range $data.Rules}}
		rule = ast.MustParse("{{.Raw}}")
		
		{{$samples := ExtractSamples .Raw}}
		for _, sample := range {{printf "%#v" $samples}} {
			op := NewOperands(sample)
			assert.True(t, evaluate(rule, op), sample)
		}
	{{end}}
}
{{end}}
`))
