// This file is generated by cldrplural/generator/generate.sh; DO NOT EDIT
package cldrplural

import (
	"testing"

	"golang.org/x/text/language"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestPrebuildLt(t *testing.T) {
	for _, lang := range []string{"lt"} {
		set, found := prebuildRuleSets[language.MustParse(lang)]
		require.True(t, found)

		for _, sample := range []string{"1", "21", "31", "41", "51", "61", "71", "81", "101", "1001", "1.0", "21.0", "31.0", "41.0", "51.0", "61.0", "71.0", "81.0", "101.0", "1001.0"} {
			op := ExtractOperands(sample)
			assert.Equal(t, One, set.FormFunc(op))
		}

		for _, sample := range []string{"2", "3", "4", "5", "6", "7", "8", "9", "22", "23", "24", "25", "26", "27", "28", "29", "102", "1002", "2.0", "3.0", "4.0", "5.0", "6.0", "7.0", "8.0", "9.0", "22.0", "102.0", "1002.0"} {
			op := ExtractOperands(sample)
			assert.Equal(t, Few, set.FormFunc(op))
		}

		for _, sample := range []string{"0.1", "0.2", "0.3", "0.4", "0.5", "0.6", "0.7", "0.8", "0.9", "1.1", "1.2", "1.3", "1.4", "1.5", "1.6", "1.7", "10.1", "100.1", "1000.1"} {
			op := ExtractOperands(sample)
			assert.Equal(t, Many, set.FormFunc(op))
		}

		for _, sample := range []string{"0", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "30", "40", "50", "60", "100", "1000", "10000", "100000", "1000000", "0.0", "10.0", "11.0", "12.0", "13.0", "14.0", "15.0", "16.0", "100.0", "1000.0", "10000.0", "100000.0", "1000000.0"} {
			op := ExtractOperands(sample)
			assert.Equal(t, Other, set.FormFunc(op))
		}

	}
}

func TestPrebuildPt_PTIt(t *testing.T) {
	for _, lang := range []string{"pt-PT", "it"} {
		set, found := prebuildRuleSets[language.MustParse(lang)]
		require.True(t, found)

		for _, sample := range []string{"1"} {
			op := ExtractOperands(sample)
			assert.Equal(t, One, set.FormFunc(op))
		}

		for _, sample := range []string{"1000000", "1c6", "2c6", "3c6", "4c6", "5c6", "6c6", "1.0000001c6", "1.1c6", "2.0000001c6", "2.1c6", "3.0000001c6", "3.1c6"} {
			op := ExtractOperands(sample)
			assert.Equal(t, Many, set.FormFunc(op))
		}

		for _, sample := range []string{"0", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "100", "1000", "10000", "100000", "1c3", "2c3", "3c3", "4c3", "5c3", "6c3", "0.0", "0.1", "0.2", "0.3", "0.4", "0.5", "0.6", "0.7", "0.8", "0.9", "1.0", "1.1", "1.2", "1.3", "1.4", "1.5", "10.0", "100.0", "1000.0", "10000.0", "100000.0", "1000000.0", "1.0001c3", "1.1c3", "2.0001c3", "2.1c3", "3.0001c3", "3.1c3"} {
			op := ExtractOperands(sample)
			assert.Equal(t, Other, set.FormFunc(op))
		}

	}
}

func TestPrebuildNlAstDeEnEtScFyLijSwIoScnIaGlFiUrCaSvYi(t *testing.T) {
	for _, lang := range []string{"nl", "ast", "de", "en", "et", "sc", "fy", "lij", "sw", "io", "scn", "ia", "gl", "fi", "ur", "ca", "sv", "yi"} {
		set, found := prebuildRuleSets[language.MustParse(lang)]
		require.True(t, found)

		for _, sample := range []string{"1"} {
			op := ExtractOperands(sample)
			assert.Equal(t, One, set.FormFunc(op))
		}

		for _, sample := range []string{"0", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "100", "1000", "10000", "100000", "1000000", "0.0", "0.1", "0.2", "0.3", "0.4", "0.5", "0.6", "0.7", "0.8", "0.9", "1.0", "1.1", "1.2", "1.3", "1.4", "1.5", "10.0", "100.0", "1000.0", "10000.0", "100000.0", "1000000.0"} {
			op := ExtractOperands(sample)
			assert.Equal(t, Other, set.FormFunc(op))
		}

	}
}

func TestPrebuildLag(t *testing.T) {
	for _, lang := range []string{"lag"} {
		set, found := prebuildRuleSets[language.MustParse(lang)]
		require.True(t, found)

		for _, sample := range []string{"0", "0.0", "0.00", "0.000", "0.0000"} {
			op := ExtractOperands(sample)
			assert.Equal(t, Zero, set.FormFunc(op))
		}

		for _, sample := range []string{"1", "0.1", "0.2", "0.3", "0.4", "0.5", "0.6", "0.7", "0.8", "0.9", "1.0", "1.1", "1.2", "1.3", "1.4", "1.5", "1.6"} {
			op := ExtractOperands(sample)
			assert.Equal(t, One, set.FormFunc(op))
		}

		for _, sample := range []string{"2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "100", "1000", "10000", "100000", "1000000", "2.0", "2.1", "2.2", "2.3", "2.4", "2.5", "2.6", "2.7", "2.8", "2.9", "3.0", "3.1", "3.2", "3.3", "3.4", "3.5", "10.0", "100.0", "1000.0", "10000.0", "100000.0", "1000000.0"} {
			op := ExtractOperands(sample)
			assert.Equal(t, Other, set.FormFunc(op))
		}

	}
}

func TestPrebuildGv(t *testing.T) {
	for _, lang := range []string{"gv"} {
		set, found := prebuildRuleSets[language.MustParse(lang)]
		require.True(t, found)

		for _, sample := range []string{"1", "11", "21", "31", "41", "51", "61", "71", "101", "1001"} {
			op := ExtractOperands(sample)
			assert.Equal(t, One, set.FormFunc(op))
		}

		for _, sample := range []string{"2", "12", "22", "32", "42", "52", "62", "72", "102", "1002"} {
			op := ExtractOperands(sample)
			assert.Equal(t, Two, set.FormFunc(op))
		}

		for _, sample := range []string{"0", "20", "40", "60", "80", "100", "120", "140", "1000", "10000", "100000", "1000000"} {
			op := ExtractOperands(sample)
			assert.Equal(t, Few, set.FormFunc(op))
		}

		for _, sample := range []string{"0.0", "0.1", "0.2", "0.3", "0.4", "0.5", "0.6", "0.7", "0.8", "0.9", "1.0", "1.1", "1.2", "1.3", "1.4", "1.5", "10.0", "100.0", "1000.0", "10000.0", "100000.0", "1000000.0"} {
			op := ExtractOperands(sample)
			assert.Equal(t, Many, set.FormFunc(op))
		}

		for _, sample := range []string{"3", "4", "5", "6", "7", "8", "9", "10", "13", "14", "15", "16", "17", "18", "19", "23", "103", "1003"} {
			op := ExtractOperands(sample)
			assert.Equal(t, Other, set.FormFunc(op))
		}

	}
}

func TestPrebuildPt(t *testing.T) {
	for _, lang := range []string{"pt"} {
		set, found := prebuildRuleSets[language.MustParse(lang)]
		require.True(t, found)

		for _, sample := range []string{"0", "1", "0.0", "0.1", "0.2", "0.3", "0.4", "0.5", "0.6", "0.7", "0.8", "0.9", "1.0", "1.1", "1.2", "1.3", "1.4", "1.5"} {
			op := ExtractOperands(sample)
			assert.Equal(t, One, set.FormFunc(op))
		}

		for _, sample := range []string{"1000000", "1c6", "2c6", "3c6", "4c6", "5c6", "6c6", "1.0000001c6", "1.1c6", "2.0000001c6", "2.1c6", "3.0000001c6", "3.1c6"} {
			op := ExtractOperands(sample)
			assert.Equal(t, Many, set.FormFunc(op))
		}

		for _, sample := range []string{"2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "100", "1000", "10000", "100000", "1c3", "2c3", "3c3", "4c3", "5c3", "6c3", "2.0", "2.1", "2.2", "2.3", "2.4", "2.5", "2.6", "2.7", "2.8", "2.9", "3.0", "3.1", "3.2", "3.3", "3.4", "3.5", "10.0", "100.0", "1000.0", "10000.0", "100000.0", "1000000.0", "1.0001c3", "1.1c3", "2.0001c3", "2.1c3", "3.0001c3", "3.1c3"} {
			op := ExtractOperands(sample)
			assert.Equal(t, Other, set.FormFunc(op))
		}

	}
}

func TestPrebuildEs(t *testing.T) {
	for _, lang := range []string{"es"} {
		set, found := prebuildRuleSets[language.MustParse(lang)]
		require.True(t, found)

		for _, sample := range []string{"1", "1.0", "1.00", "1.000", "1.0000"} {
			op := ExtractOperands(sample)
			assert.Equal(t, One, set.FormFunc(op))
		}

		for _, sample := range []string{"1000000", "1c6", "2c6", "3c6", "4c6", "5c6", "6c6", "1.0000001c6", "1.1c6", "2.0000001c6", "2.1c6", "3.0000001c6", "3.1c6"} {
			op := ExtractOperands(sample)
			assert.Equal(t, Many, set.FormFunc(op))
		}

		for _, sample := range []string{"0", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "100", "1000", "10000", "100000", "1c3", "2c3", "3c3", "4c3", "5c3", "6c3", "0.0", "0.1", "0.2", "0.3", "0.4", "0.5", "0.6", "0.7", "0.8", "0.9", "1.1", "1.2", "1.3", "1.4", "1.5", "1.6", "10.0", "100.0", "1000.0", "10000.0", "100000.0", "1000000.0", "1.0001c3", "1.1c3", "2.0001c3", "2.1c3", "3.0001c3", "3.1c3"} {
			op := ExtractOperands(sample)
			assert.Equal(t, Other, set.FormFunc(op))
		}

	}
}

func TestPrebuildBe(t *testing.T) {
	for _, lang := range []string{"be"} {
		set, found := prebuildRuleSets[language.MustParse(lang)]
		require.True(t, found)

		for _, sample := range []string{"1", "21", "31", "41", "51", "61", "71", "81", "101", "1001", "1.0", "21.0", "31.0", "41.0", "51.0", "61.0", "71.0", "81.0", "101.0", "1001.0"} {
			op := ExtractOperands(sample)
			assert.Equal(t, One, set.FormFunc(op))
		}

		for _, sample := range []string{"2", "3", "4", "22", "23", "24", "32", "33", "34", "42", "43", "44", "52", "53", "54", "62", "102", "1002", "2.0", "3.0", "4.0", "22.0", "23.0", "24.0", "32.0", "33.0", "102.0", "1002.0"} {
			op := ExtractOperands(sample)
			assert.Equal(t, Few, set.FormFunc(op))
		}

		for _, sample := range []string{"0", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "100", "1000", "10000", "100000", "1000000", "0.0", "5.0", "6.0", "7.0", "8.0", "9.0", "10.0", "11.0", "100.0", "1000.0", "10000.0", "100000.0", "1000000.0"} {
			op := ExtractOperands(sample)
			assert.Equal(t, Many, set.FormFunc(op))
		}

		for _, sample := range []string{"0.1", "0.2", "0.3", "0.4", "0.5", "0.6", "0.7", "0.8", "0.9", "1.1", "1.2", "1.3", "1.4", "1.5", "1.6", "1.7", "10.1", "100.1", "1000.1"} {
			op := ExtractOperands(sample)
			assert.Equal(t, Other, set.FormFunc(op))
		}

	}
}

func TestPrebuildSmnSmsSmaSmiSmjNaqSatSeIu(t *testing.T) {
	for _, lang := range []string{"smn", "sms", "sma", "smi", "smj", "naq", "sat", "se", "iu"} {
		set, found := prebuildRuleSets[language.MustParse(lang)]
		require.True(t, found)

		for _, sample := range []string{"1", "1.0", "1.00", "1.000", "1.0000"} {
			op := ExtractOperands(sample)
			assert.Equal(t, One, set.FormFunc(op))
		}

		for _, sample := range []string{"2", "2.0", "2.00", "2.000", "2.0000"} {
			op := ExtractOperands(sample)
			assert.Equal(t, Two, set.FormFunc(op))
		}

		for _, sample := range []string{"0", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "100", "1000", "10000", "100000", "1000000", "0.0", "0.1", "0.2", "0.3", "0.4", "0.5", "0.6", "0.7", "0.8", "0.9", "1.1", "1.2", "1.3", "1.4", "1.5", "1.6", "10.0", "100.0", "1000.0", "10000.0", "100000.0", "1000000.0"} {
			op := ExtractOperands(sample)
			assert.Equal(t, Other, set.FormFunc(op))
		}

	}
}

func TestPrebuildWaNsoTiPaBhoGuwAkMgLn(t *testing.T) {
	for _, lang := range []string{"wa", "nso", "ti", "pa", "bho", "guw", "ak", "mg", "ln"} {
		set, found := prebuildRuleSets[language.MustParse(lang)]
		require.True(t, found)

		for _, sample := range []string{"0", "1", "0.0", "1.0", "0.00", "1.00", "0.000", "1.000", "0.0000", "1.0000"} {
			op := ExtractOperands(sample)
			assert.Equal(t, One, set.FormFunc(op))
		}

		for _, sample := range []string{"2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "100", "1000", "10000", "100000", "1000000", "0.1", "0.2", "0.3", "0.4", "0.5", "0.6", "0.7", "0.8", "0.9", "1.1", "1.2", "1.3", "1.4", "1.5", "1.6", "1.7", "10.0", "100.0", "1000.0", "10000.0", "100000.0", "1000000.0"} {
			op := ExtractOperands(sample)
			assert.Equal(t, Other, set.FormFunc(op))
		}

	}
}

func TestPrebuildKw(t *testing.T) {
	for _, lang := range []string{"kw"} {
		set, found := prebuildRuleSets[language.MustParse(lang)]
		require.True(t, found)

		for _, sample := range []string{"0", "0.0", "0.00", "0.000", "0.0000"} {
			op := ExtractOperands(sample)
			assert.Equal(t, Zero, set.FormFunc(op))
		}

		for _, sample := range []string{"1", "1.0", "1.00", "1.000", "1.0000"} {
			op := ExtractOperands(sample)
			assert.Equal(t, One, set.FormFunc(op))
		}

		for _, sample := range []string{"2", "22", "42", "62", "82", "102", "122", "142", "1000", "10000", "100000", "2.0", "22.0", "42.0", "62.0", "82.0", "102.0", "122.0", "142.0", "1000.0", "10000.0", "100000.0"} {
			op := ExtractOperands(sample)
			assert.Equal(t, Two, set.FormFunc(op))
		}

		for _, sample := range []string{"3", "23", "43", "63", "83", "103", "123", "143", "1003", "3.0", "23.0", "43.0", "63.0", "83.0", "103.0", "123.0", "143.0", "1003.0"} {
			op := ExtractOperands(sample)
			assert.Equal(t, Few, set.FormFunc(op))
		}

		for _, sample := range []string{"21", "41", "61", "81", "101", "121", "141", "161", "1001", "21.0", "41.0", "61.0", "81.0", "101.0", "121.0", "141.0", "161.0", "1001.0"} {
			op := ExtractOperands(sample)
			assert.Equal(t, Many, set.FormFunc(op))
		}

		for _, sample := range []string{"4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "100", "1004", "1000000", "0.1", "0.2", "0.3", "0.4", "0.5", "0.6", "0.7", "0.8", "0.9", "1.1", "1.2", "1.3", "1.4", "1.5", "1.6", "1.7", "10.0", "100.0", "1000.1", "1000000.0"} {
			op := ExtractOperands(sample)
			assert.Equal(t, Other, set.FormFunc(op))
		}

	}
}

func TestPrebuildRoMo(t *testing.T) {
	for _, lang := range []string{"ro", "mo"} {
		set, found := prebuildRuleSets[language.MustParse(lang)]
		require.True(t, found)

		for _, sample := range []string{"1"} {
			op := ExtractOperands(sample)
			assert.Equal(t, One, set.FormFunc(op))
		}

		for _, sample := range []string{"0", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "102", "1002", "0.0", "0.1", "0.2", "0.3", "0.4", "0.5", "0.6", "0.7", "0.8", "0.9", "1.0", "1.1", "1.2", "1.3", "1.4", "1.5", "10.0", "100.0", "1000.0", "10000.0", "100000.0", "1000000.0"} {
			op := ExtractOperands(sample)
			assert.Equal(t, Few, set.FormFunc(op))
		}

		for _, sample := range []string{"20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "100", "1000", "10000", "100000", "1000000"} {
			op := ExtractOperands(sample)
			assert.Equal(t, Other, set.FormFunc(op))
		}

	}
}

func TestPrebuildHe(t *testing.T) {
	for _, lang := range []string{"he"} {
		set, found := prebuildRuleSets[language.MustParse(lang)]
		require.True(t, found)

		for _, sample := range []string{"1"} {
			op := ExtractOperands(sample)
			assert.Equal(t, One, set.FormFunc(op))
		}

		for _, sample := range []string{"2"} {
			op := ExtractOperands(sample)
			assert.Equal(t, Two, set.FormFunc(op))
		}

		for _, sample := range []string{"20", "30", "40", "50", "60", "70", "80", "90", "100", "1000", "10000", "100000", "1000000"} {
			op := ExtractOperands(sample)
			assert.Equal(t, Many, set.FormFunc(op))
		}

		for _, sample := range []string{"0", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "101", "1001", "0.0", "0.1", "0.2", "0.3", "0.4", "0.5", "0.6", "0.7", "0.8", "0.9", "1.0", "1.1", "1.2", "1.3", "1.4", "1.5", "10.0", "100.0", "1000.0", "10000.0", "100000.0", "1000000.0"} {
			op := ExtractOperands(sample)
			assert.Equal(t, Other, set.FormFunc(op))
		}

	}
}

func TestPrebuildToLoUndJboBmSesIgIiMyJwKmYoHnjJaNqoMsThKoTpiBoKeaZhLktIdViSahSuOsaKdeDzJvYueWoSg(t *testing.T) {
	for _, lang := range []string{"to", "lo", "und", "jbo", "bm", "ses", "ig", "ii", "my", "jw", "km", "yo", "hnj", "ja", "nqo", "ms", "th", "ko", "tpi", "bo", "kea", "zh", "lkt", "id", "vi", "sah", "su", "osa", "kde", "dz", "jv", "yue", "wo", "sg"} {
		set, found := prebuildRuleSets[language.MustParse(lang)]
		require.True(t, found)

		for _, sample := range []string{"0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "100", "1000", "10000", "100000", "1000000", "0.0", "0.1", "0.2", "0.3", "0.4", "0.5", "0.6", "0.7", "0.8", "0.9", "1.0", "1.1", "1.2", "1.3", "1.4", "1.5", "10.0", "100.0", "1000.0", "10000.0", "100000.0", "1000000.0"} {
			op := ExtractOperands(sample)
			assert.Equal(t, Other, set.FormFunc(op))
		}

	}
}

func TestPrebuildPcmAmAsZuKnDoiFaHiGuBn(t *testing.T) {
	for _, lang := range []string{"pcm", "am", "as", "zu", "kn", "doi", "fa", "hi", "gu", "bn"} {
		set, found := prebuildRuleSets[language.MustParse(lang)]
		require.True(t, found)

		for _, sample := range []string{"0", "1", "0.0", "0.1", "0.2", "0.3", "0.4", "0.5", "0.6", "0.7", "0.8", "0.9", "1.0", "0.00", "0.01", "0.02", "0.03", "0.04"} {
			op := ExtractOperands(sample)
			assert.Equal(t, One, set.FormFunc(op))
		}

		for _, sample := range []string{"2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "100", "1000", "10000", "100000", "1000000", "1.1", "1.2", "1.3", "1.4", "1.5", "1.6", "1.7", "1.8", "1.9", "2.0", "2.1", "2.2", "2.3", "2.4", "2.5", "2.6", "10.0", "100.0", "1000.0", "10000.0", "100000.0", "1000000.0"} {
			op := ExtractOperands(sample)
			assert.Equal(t, Other, set.FormFunc(op))
		}

	}
}

func TestPrebuildGd(t *testing.T) {
	for _, lang := range []string{"gd"} {
		set, found := prebuildRuleSets[language.MustParse(lang)]
		require.True(t, found)

		for _, sample := range []string{"1", "11", "1.0", "11.0", "1.00", "11.00", "1.000", "11.000", "1.0000"} {
			op := ExtractOperands(sample)
			assert.Equal(t, One, set.FormFunc(op))
		}

		for _, sample := range []string{"2", "12", "2.0", "12.0", "2.00", "12.00", "2.000", "12.000", "2.0000"} {
			op := ExtractOperands(sample)
			assert.Equal(t, Two, set.FormFunc(op))
		}

		for _, sample := range []string{"3", "4", "5", "6", "7", "8", "9", "10", "13", "14", "15", "16", "17", "18", "19", "3.0", "4.0", "5.0", "6.0", "7.0", "8.0", "9.0", "10.0", "13.0", "14.0", "15.0", "16.0", "17.0", "18.0", "19.0", "3.00"} {
			op := ExtractOperands(sample)
			assert.Equal(t, Few, set.FormFunc(op))
		}

		for _, sample := range []string{"0", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "100", "1000", "10000", "100000", "1000000", "0.0", "0.1", "0.2", "0.3", "0.4", "0.5", "0.6", "0.7", "0.8", "0.9", "1.1", "1.2", "1.3", "1.4", "1.5", "1.6", "10.1", "100.0", "1000.0", "10000.0", "100000.0", "1000000.0"} {
			op := ExtractOperands(sample)
			assert.Equal(t, Other, set.FormFunc(op))
		}

	}
}

func TestPrebuildSl(t *testing.T) {
	for _, lang := range []string{"sl"} {
		set, found := prebuildRuleSets[language.MustParse(lang)]
		require.True(t, found)

		for _, sample := range []string{"1", "101", "201", "301", "401", "501", "601", "701", "1001"} {
			op := ExtractOperands(sample)
			assert.Equal(t, One, set.FormFunc(op))
		}

		for _, sample := range []string{"2", "102", "202", "302", "402", "502", "602", "702", "1002"} {
			op := ExtractOperands(sample)
			assert.Equal(t, Two, set.FormFunc(op))
		}

		for _, sample := range []string{"3", "4", "103", "104", "203", "204", "303", "304", "403", "404", "503", "504", "603", "604", "703", "704", "1003", "0.0", "0.1", "0.2", "0.3", "0.4", "0.5", "0.6", "0.7", "0.8", "0.9", "1.0", "1.1", "1.2", "1.3", "1.4", "1.5", "10.0", "100.0", "1000.0", "10000.0", "100000.0", "1000000.0"} {
			op := ExtractOperands(sample)
			assert.Equal(t, Few, set.FormFunc(op))
		}

		for _, sample := range []string{"0", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "100", "1000", "10000", "100000", "1000000"} {
			op := ExtractOperands(sample)
			assert.Equal(t, Other, set.FormFunc(op))
		}

	}
}

func TestPrebuildDa(t *testing.T) {
	for _, lang := range []string{"da"} {
		set, found := prebuildRuleSets[language.MustParse(lang)]
		require.True(t, found)

		for _, sample := range []string{"1", "0.1", "0.2", "0.3", "0.4", "0.5", "0.6", "0.7", "0.8", "0.9", "1.0", "1.1", "1.2", "1.3", "1.4", "1.5", "1.6"} {
			op := ExtractOperands(sample)
			assert.Equal(t, One, set.FormFunc(op))
		}

		for _, sample := range []string{"0", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "100", "1000", "10000", "100000", "1000000", "0.0", "2.0", "2.1", "2.2", "2.3", "2.4", "2.5", "2.6", "2.7", "2.8", "2.9", "3.0", "3.1", "3.2", "3.3", "3.4", "10.0", "100.0", "1000.0", "10000.0", "100000.0", "1000000.0"} {
			op := ExtractOperands(sample)
			assert.Equal(t, Other, set.FormFunc(op))
		}

	}
}

func TestPrebuildIs(t *testing.T) {
	for _, lang := range []string{"is"} {
		set, found := prebuildRuleSets[language.MustParse(lang)]
		require.True(t, found)

		for _, sample := range []string{"1", "21", "31", "41", "51", "61", "71", "81", "101", "1001", "0.1", "0.2", "0.3", "0.4", "0.5", "0.6", "0.7", "0.8", "0.9", "1.0", "1.1", "1.2", "1.3", "1.4", "1.5", "1.6", "10.1", "100.1", "1000.1"} {
			op := ExtractOperands(sample)
			assert.Equal(t, One, set.FormFunc(op))
		}

		for _, sample := range []string{"0", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "100", "1000", "10000", "100000", "1000000", "0.0", "2.0", "3.0", "4.0", "5.0", "6.0", "7.0", "8.0", "10.0", "100.0", "1000.0", "10000.0", "100000.0", "1000000.0"} {
			op := ExtractOperands(sample)
			assert.Equal(t, Other, set.FormFunc(op))
		}

	}
}

func TestPrebuildArArs(t *testing.T) {
	for _, lang := range []string{"ar", "ars"} {
		set, found := prebuildRuleSets[language.MustParse(lang)]
		require.True(t, found)

		for _, sample := range []string{"0", "0.0", "0.00", "0.000", "0.0000"} {
			op := ExtractOperands(sample)
			assert.Equal(t, Zero, set.FormFunc(op))
		}

		for _, sample := range []string{"1", "1.0", "1.00", "1.000", "1.0000"} {
			op := ExtractOperands(sample)
			assert.Equal(t, One, set.FormFunc(op))
		}

		for _, sample := range []string{"2", "2.0", "2.00", "2.000", "2.0000"} {
			op := ExtractOperands(sample)
			assert.Equal(t, Two, set.FormFunc(op))
		}

		for _, sample := range []string{"3", "4", "5", "6", "7", "8", "9", "10", "103", "104", "105", "106", "107", "108", "109", "110", "1003", "3.0", "4.0", "5.0", "6.0", "7.0", "8.0", "9.0", "10.0", "103.0", "1003.0"} {
			op := ExtractOperands(sample)
			assert.Equal(t, Few, set.FormFunc(op))
		}

		for _, sample := range []string{"11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "111", "1011", "11.0", "12.0", "13.0", "14.0", "15.0", "16.0", "17.0", "18.0", "111.0", "1011.0"} {
			op := ExtractOperands(sample)
			assert.Equal(t, Many, set.FormFunc(op))
		}

		for _, sample := range []string{"100", "101", "102", "200", "201", "202", "300", "301", "302", "400", "401", "402", "500", "501", "502", "600", "1000", "10000", "100000", "1000000", "0.1", "0.2", "0.3", "0.4", "0.5", "0.6", "0.7", "0.8", "0.9", "1.1", "1.2", "1.3", "1.4", "1.5", "1.6", "1.7", "10.1", "100.0", "1000.0", "10000.0", "100000.0", "1000000.0"} {
			op := ExtractOperands(sample)
			assert.Equal(t, Other, set.FormFunc(op))
		}

	}
}

func TestPrebuildFilCebTl(t *testing.T) {
	for _, lang := range []string{"fil", "ceb", "tl"} {
		set, found := prebuildRuleSets[language.MustParse(lang)]
		require.True(t, found)

		for _, sample := range []string{"0", "1", "2", "3", "5", "7", "8", "10", "11", "12", "13", "15", "17", "18", "20", "21", "100", "1000", "10000", "100000", "1000000", "0.0", "0.1", "0.2", "0.3", "0.5", "0.7", "0.8", "1.0", "1.1", "1.2", "1.3", "1.5", "1.7", "1.8", "2.0", "2.1", "10.0", "100.0", "1000.0", "10000.0", "100000.0", "1000000.0"} {
			op := ExtractOperands(sample)
			assert.Equal(t, One, set.FormFunc(op))
		}

		for _, sample := range []string{"4", "6", "9", "14", "16", "19", "24", "26", "104", "1004", "0.4", "0.6", "0.9", "1.4", "1.6", "1.9", "2.4", "2.6", "10.4", "100.4", "1000.4"} {
			op := ExtractOperands(sample)
			assert.Equal(t, Other, set.FormFunc(op))
		}

	}
}

func TestPrebuildBr(t *testing.T) {
	for _, lang := range []string{"br"} {
		set, found := prebuildRuleSets[language.MustParse(lang)]
		require.True(t, found)

		for _, sample := range []string{"1", "21", "31", "41", "51", "61", "81", "101", "1001", "1.0", "21.0", "31.0", "41.0", "51.0", "61.0", "81.0", "101.0", "1001.0"} {
			op := ExtractOperands(sample)
			assert.Equal(t, One, set.FormFunc(op))
		}

		for _, sample := range []string{"2", "22", "32", "42", "52", "62", "82", "102", "1002", "2.0", "22.0", "32.0", "42.0", "52.0", "62.0", "82.0", "102.0", "1002.0"} {
			op := ExtractOperands(sample)
			assert.Equal(t, Two, set.FormFunc(op))
		}

		for _, sample := range []string{"3", "4", "9", "23", "24", "29", "33", "34", "39", "43", "44", "49", "103", "1003", "3.0", "4.0", "9.0", "23.0", "24.0", "29.0", "33.0", "34.0", "103.0", "1003.0"} {
			op := ExtractOperands(sample)
			assert.Equal(t, Few, set.FormFunc(op))
		}

		for _, sample := range []string{"1000000", "1000000.0", "1000000.00", "1000000.000", "1000000.0000"} {
			op := ExtractOperands(sample)
			assert.Equal(t, Many, set.FormFunc(op))
		}

		for _, sample := range []string{"0", "5", "6", "7", "8", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "100", "1000", "10000", "100000", "0.0", "0.1", "0.2", "0.3", "0.4", "0.5", "0.6", "0.7", "0.8", "0.9", "1.1", "1.2", "1.3", "1.4", "1.5", "1.6", "10.0", "100.0", "1000.0", "10000.0", "100000.0"} {
			op := ExtractOperands(sample)
			assert.Equal(t, Other, set.FormFunc(op))
		}

	}
}

func TestPrebuildFr(t *testing.T) {
	for _, lang := range []string{"fr"} {
		set, found := prebuildRuleSets[language.MustParse(lang)]
		require.True(t, found)

		for _, sample := range []string{"0", "1", "0.0", "0.1", "0.2", "0.3", "0.4", "0.5", "0.6", "0.7", "0.8", "0.9", "1.0", "1.1", "1.2", "1.3", "1.4", "1.5"} {
			op := ExtractOperands(sample)
			assert.Equal(t, One, set.FormFunc(op))
		}

		for _, sample := range []string{"1000000", "1c6", "2c6", "3c6", "4c6", "5c6", "6c6", "1.0000001c6", "1.1c6", "2.0000001c6", "2.1c6", "3.0000001c6", "3.1c6"} {
			op := ExtractOperands(sample)
			assert.Equal(t, Many, set.FormFunc(op))
		}

		for _, sample := range []string{"2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "100", "1000", "10000", "100000", "1c3", "2c3", "3c3", "4c3", "5c3", "6c3", "2.0", "2.1", "2.2", "2.3", "2.4", "2.5", "2.6", "2.7", "2.8", "2.9", "3.0", "3.1", "3.2", "3.3", "3.4", "3.5", "10.0", "100.0", "1000.0", "10000.0", "100000.0", "1000000.0", "1.0001c3", "1.1c3", "2.0001c3", "2.1c3", "3.0001c3", "3.1c3"} {
			op := ExtractOperands(sample)
			assert.Equal(t, Other, set.FormFunc(op))
		}

	}
}

func TestPrebuildMk(t *testing.T) {
	for _, lang := range []string{"mk"} {
		set, found := prebuildRuleSets[language.MustParse(lang)]
		require.True(t, found)

		for _, sample := range []string{"1", "21", "31", "41", "51", "61", "71", "81", "101", "1001", "0.1", "1.1", "2.1", "3.1", "4.1", "5.1", "6.1", "7.1", "10.1", "100.1", "1000.1"} {
			op := ExtractOperands(sample)
			assert.Equal(t, One, set.FormFunc(op))
		}

		for _, sample := range []string{"0", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "100", "1000", "10000", "100000", "1000000", "0.0", "0.2", "0.3", "0.4", "0.5", "0.6", "0.7", "0.8", "0.9", "1.0", "1.2", "1.3", "1.4", "1.5", "1.6", "1.7", "10.0", "100.0", "1000.0", "10000.0", "100000.0", "1000000.0"} {
			op := ExtractOperands(sample)
			assert.Equal(t, Other, set.FormFunc(op))
		}

	}
}

func TestPrebuildKyFurSdhXhCeNnhPsRofPapStAsaHuAfBalGswSsyTigBezCkbNyBrxVoCggKkTnTsUgMgoMnVeSaqEoVunLgTkTrKsRwkNeElHawKlRmNnEeNoNrKkjOsTaJmcJgoMasOrWaeSdBgDvKsbKajSoKuNbAnNynEuKcgMrXogKaNdFoOmSqMlSnSyrBemSehAzChrSsTeLbNahUzHaTeo(t *testing.T) {
	for _, lang := range []string{"ky", "fur", "sdh", "xh", "ce", "nnh", "ps", "rof", "pap", "st", "asa", "hu", "af", "bal", "gsw", "ssy", "tig", "bez", "ckb", "ny", "brx", "vo", "cgg", "kk", "tn", "ts", "ug", "mgo", "mn", "ve", "saq", "eo", "vun", "lg", "tk", "tr", "ks", "rwk", "ne", "el", "haw", "kl", "rm", "nn", "ee", "no", "nr", "kkj", "os", "ta", "jmc", "jgo", "mas", "or", "wae", "sd", "bg", "dv", "ksb", "kaj", "so", "ku", "nb", "an", "nyn", "eu", "kcg", "mr", "xog", "ka", "nd", "fo", "om", "sq", "ml", "sn", "syr", "bem", "seh", "az", "chr", "ss", "te", "lb", "nah", "uz", "ha", "teo"} {
		set, found := prebuildRuleSets[language.MustParse(lang)]
		require.True(t, found)

		for _, sample := range []string{"1", "1.0", "1.00", "1.000", "1.0000"} {
			op := ExtractOperands(sample)
			assert.Equal(t, One, set.FormFunc(op))
		}

		for _, sample := range []string{"0", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "100", "1000", "10000", "100000", "1000000", "0.0", "0.1", "0.2", "0.3", "0.4", "0.5", "0.6", "0.7", "0.8", "0.9", "1.1", "1.2", "1.3", "1.4", "1.5", "1.6", "10.0", "100.0", "1000.0", "10000.0", "100000.0", "1000000.0"} {
			op := ExtractOperands(sample)
			assert.Equal(t, Other, set.FormFunc(op))
		}

	}
}

func TestPrebuildCsSk(t *testing.T) {
	for _, lang := range []string{"cs", "sk"} {
		set, found := prebuildRuleSets[language.MustParse(lang)]
		require.True(t, found)

		for _, sample := range []string{"1"} {
			op := ExtractOperands(sample)
			assert.Equal(t, One, set.FormFunc(op))
		}

		for _, sample := range []string{"2", "3", "4"} {
			op := ExtractOperands(sample)
			assert.Equal(t, Few, set.FormFunc(op))
		}

		for _, sample := range []string{"0.0", "0.1", "0.2", "0.3", "0.4", "0.5", "0.6", "0.7", "0.8", "0.9", "1.0", "1.1", "1.2", "1.3", "1.4", "1.5", "10.0", "100.0", "1000.0", "10000.0", "100000.0", "1000000.0"} {
			op := ExtractOperands(sample)
			assert.Equal(t, Many, set.FormFunc(op))
		}

		for _, sample := range []string{"0", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "100", "1000", "10000", "100000", "1000000"} {
			op := ExtractOperands(sample)
			assert.Equal(t, Other, set.FormFunc(op))
		}

	}
}

func TestPrebuildPl(t *testing.T) {
	for _, lang := range []string{"pl"} {
		set, found := prebuildRuleSets[language.MustParse(lang)]
		require.True(t, found)

		for _, sample := range []string{"1"} {
			op := ExtractOperands(sample)
			assert.Equal(t, One, set.FormFunc(op))
		}

		for _, sample := range []string{"2", "3", "4", "22", "23", "24", "32", "33", "34", "42", "43", "44", "52", "53", "54", "62", "102", "1002"} {
			op := ExtractOperands(sample)
			assert.Equal(t, Few, set.FormFunc(op))
		}

		for _, sample := range []string{"0", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "100", "1000", "10000", "100000", "1000000"} {
			op := ExtractOperands(sample)
			assert.Equal(t, Many, set.FormFunc(op))
		}

		for _, sample := range []string{"0.0", "0.1", "0.2", "0.3", "0.4", "0.5", "0.6", "0.7", "0.8", "0.9", "1.0", "1.1", "1.2", "1.3", "1.4", "1.5", "10.0", "100.0", "1000.0", "10000.0", "100000.0", "1000000.0"} {
			op := ExtractOperands(sample)
			assert.Equal(t, Other, set.FormFunc(op))
		}

	}
}

func TestPrebuildDsbHsb(t *testing.T) {
	for _, lang := range []string{"dsb", "hsb"} {
		set, found := prebuildRuleSets[language.MustParse(lang)]
		require.True(t, found)

		for _, sample := range []string{"1", "101", "201", "301", "401", "501", "601", "701", "1001", "0.1", "1.1", "2.1", "3.1", "4.1", "5.1", "6.1", "7.1", "10.1", "100.1", "1000.1"} {
			op := ExtractOperands(sample)
			assert.Equal(t, One, set.FormFunc(op))
		}

		for _, sample := range []string{"2", "102", "202", "302", "402", "502", "602", "702", "1002", "0.2", "1.2", "2.2", "3.2", "4.2", "5.2", "6.2", "7.2", "10.2", "100.2", "1000.2"} {
			op := ExtractOperands(sample)
			assert.Equal(t, Two, set.FormFunc(op))
		}

		for _, sample := range []string{"3", "4", "103", "104", "203", "204", "303", "304", "403", "404", "503", "504", "603", "604", "703", "704", "1003", "0.3", "0.4", "1.3", "1.4", "2.3", "2.4", "3.3", "3.4", "4.3", "4.4", "5.3", "5.4", "6.3", "6.4", "7.3", "7.4", "10.3", "100.3", "1000.3"} {
			op := ExtractOperands(sample)
			assert.Equal(t, Few, set.FormFunc(op))
		}

		for _, sample := range []string{"0", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "100", "1000", "10000", "100000", "1000000", "0.0", "0.5", "0.6", "0.7", "0.8", "0.9", "1.0", "1.5", "1.6", "1.7", "1.8", "1.9", "2.0", "2.5", "2.6", "2.7", "10.0", "100.0", "1000.0", "10000.0", "100000.0", "1000000.0"} {
			op := ExtractOperands(sample)
			assert.Equal(t, Other, set.FormFunc(op))
		}

	}
}

func TestPrebuildSi(t *testing.T) {
	for _, lang := range []string{"si"} {
		set, found := prebuildRuleSets[language.MustParse(lang)]
		require.True(t, found)

		for _, sample := range []string{"0", "1", "0.0", "0.1", "1.0", "0.00", "0.01", "1.00", "0.000", "0.001", "1.000", "0.0000", "0.0001", "1.0000"} {
			op := ExtractOperands(sample)
			assert.Equal(t, One, set.FormFunc(op))
		}

		for _, sample := range []string{"2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "100", "1000", "10000", "100000", "1000000", "0.2", "0.3", "0.4", "0.5", "0.6", "0.7", "0.8", "0.9", "1.1", "1.2", "1.3", "1.4", "1.5", "1.6", "1.7", "1.8", "10.0", "100.0", "1000.0", "10000.0", "100000.0", "1000000.0"} {
			op := ExtractOperands(sample)
			assert.Equal(t, Other, set.FormFunc(op))
		}

	}
}

func TestPrebuildMt(t *testing.T) {
	for _, lang := range []string{"mt"} {
		set, found := prebuildRuleSets[language.MustParse(lang)]
		require.True(t, found)

		for _, sample := range []string{"1", "1.0", "1.00", "1.000", "1.0000"} {
			op := ExtractOperands(sample)
			assert.Equal(t, One, set.FormFunc(op))
		}

		for _, sample := range []string{"0", "2", "3", "4", "5", "6", "7", "8", "9", "10", "102", "103", "104", "105", "106", "107", "1002", "0.0", "2.0", "3.0", "4.0", "5.0", "6.0", "7.0", "8.0", "10.0", "102.0", "1002.0"} {
			op := ExtractOperands(sample)
			assert.Equal(t, Few, set.FormFunc(op))
		}

		for _, sample := range []string{"11", "12", "13", "14", "15", "16", "17", "18", "19", "111", "112", "113", "114", "115", "116", "117", "1011", "11.0", "12.0", "13.0", "14.0", "15.0", "16.0", "17.0", "18.0", "111.0", "1011.0"} {
			op := ExtractOperands(sample)
			assert.Equal(t, Many, set.FormFunc(op))
		}

		for _, sample := range []string{"20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "100", "1000", "10000", "100000", "1000000", "0.1", "0.2", "0.3", "0.4", "0.5", "0.6", "0.7", "0.8", "0.9", "1.1", "1.2", "1.3", "1.4", "1.5", "1.6", "1.7", "10.1", "100.0", "1000.0", "10000.0", "100000.0", "1000000.0"} {
			op := ExtractOperands(sample)
			assert.Equal(t, Other, set.FormFunc(op))
		}

	}
}

func TestPrebuildLvPrg(t *testing.T) {
	for _, lang := range []string{"lv", "prg"} {
		set, found := prebuildRuleSets[language.MustParse(lang)]
		require.True(t, found)

		for _, sample := range []string{"0", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "30", "40", "50", "60", "100", "1000", "10000", "100000", "1000000", "0.0", "10.0", "11.0", "12.0", "13.0", "14.0", "15.0", "16.0", "100.0", "1000.0", "10000.0", "100000.0", "1000000.0"} {
			op := ExtractOperands(sample)
			assert.Equal(t, Zero, set.FormFunc(op))
		}

		for _, sample := range []string{"1", "21", "31", "41", "51", "61", "71", "81", "101", "1001", "0.1", "1.0", "1.1", "2.1", "3.1", "4.1", "5.1", "6.1", "7.1", "10.1", "100.1", "1000.1"} {
			op := ExtractOperands(sample)
			assert.Equal(t, One, set.FormFunc(op))
		}

		for _, sample := range []string{"2", "3", "4", "5", "6", "7", "8", "9", "22", "23", "24", "25", "26", "27", "28", "29", "102", "1002", "0.2", "0.3", "0.4", "0.5", "0.6", "0.7", "0.8", "0.9", "1.2", "1.3", "1.4", "1.5", "1.6", "1.7", "1.8", "1.9", "10.2", "100.2", "1000.2"} {
			op := ExtractOperands(sample)
			assert.Equal(t, Other, set.FormFunc(op))
		}

	}
}

func TestPrebuildUkRu(t *testing.T) {
	for _, lang := range []string{"uk", "ru"} {
		set, found := prebuildRuleSets[language.MustParse(lang)]
		require.True(t, found)

		for _, sample := range []string{"1", "21", "31", "41", "51", "61", "71", "81", "101", "1001"} {
			op := ExtractOperands(sample)
			assert.Equal(t, One, set.FormFunc(op))
		}

		for _, sample := range []string{"2", "3", "4", "22", "23", "24", "32", "33", "34", "42", "43", "44", "52", "53", "54", "62", "102", "1002"} {
			op := ExtractOperands(sample)
			assert.Equal(t, Few, set.FormFunc(op))
		}

		for _, sample := range []string{"0", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "100", "1000", "10000", "100000", "1000000"} {
			op := ExtractOperands(sample)
			assert.Equal(t, Many, set.FormFunc(op))
		}

		for _, sample := range []string{"0.0", "0.1", "0.2", "0.3", "0.4", "0.5", "0.6", "0.7", "0.8", "0.9", "1.0", "1.1", "1.2", "1.3", "1.4", "1.5", "10.0", "100.0", "1000.0", "10000.0", "100000.0", "1000000.0"} {
			op := ExtractOperands(sample)
			assert.Equal(t, Other, set.FormFunc(op))
		}

	}
}

func TestPrebuildTzm(t *testing.T) {
	for _, lang := range []string{"tzm"} {
		set, found := prebuildRuleSets[language.MustParse(lang)]
		require.True(t, found)

		for _, sample := range []string{"0", "1", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "0.0", "1.0", "11.0", "12.0", "13.0", "14.0", "15.0", "16.0", "17.0", "18.0", "19.0", "20.0", "21.0", "22.0", "23.0", "24.0"} {
			op := ExtractOperands(sample)
			assert.Equal(t, One, set.FormFunc(op))
		}

		for _, sample := range []string{"2", "3", "4", "5", "6", "7", "8", "9", "10", "100", "101", "102", "103", "104", "105", "106", "1000", "10000", "100000", "1000000", "0.1", "0.2", "0.3", "0.4", "0.5", "0.6", "0.7", "0.8", "0.9", "1.1", "1.2", "1.3", "1.4", "1.5", "1.6", "1.7", "10.0", "100.0", "1000.0", "10000.0", "100000.0", "1000000.0"} {
			op := ExtractOperands(sample)
			assert.Equal(t, Other, set.FormFunc(op))
		}

	}
}

func TestPrebuildShi(t *testing.T) {
	for _, lang := range []string{"shi"} {
		set, found := prebuildRuleSets[language.MustParse(lang)]
		require.True(t, found)

		for _, sample := range []string{"0", "1", "0.0", "0.1", "0.2", "0.3", "0.4", "0.5", "0.6", "0.7", "0.8", "0.9", "1.0", "0.00", "0.01", "0.02", "0.03", "0.04"} {
			op := ExtractOperands(sample)
			assert.Equal(t, One, set.FormFunc(op))
		}

		for _, sample := range []string{"2", "3", "4", "5", "6", "7", "8", "9", "10", "2.0", "3.0", "4.0", "5.0", "6.0", "7.0", "8.0", "9.0", "10.0", "2.00", "3.00", "4.00", "5.00", "6.00", "7.00", "8.00"} {
			op := ExtractOperands(sample)
			assert.Equal(t, Few, set.FormFunc(op))
		}

		for _, sample := range []string{"11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "100", "1000", "10000", "100000", "1000000", "1.1", "1.2", "1.3", "1.4", "1.5", "1.6", "1.7", "1.8", "1.9", "2.1", "2.2", "2.3", "2.4", "2.5", "2.6", "2.7", "10.1", "100.0", "1000.0", "10000.0", "100000.0", "1000000.0"} {
			op := ExtractOperands(sample)
			assert.Equal(t, Other, set.FormFunc(op))
		}

	}
}

func TestPrebuildSrBsShHr(t *testing.T) {
	for _, lang := range []string{"sr", "bs", "sh", "hr"} {
		set, found := prebuildRuleSets[language.MustParse(lang)]
		require.True(t, found)

		for _, sample := range []string{"1", "21", "31", "41", "51", "61", "71", "81", "101", "1001", "0.1", "1.1", "2.1", "3.1", "4.1", "5.1", "6.1", "7.1", "10.1", "100.1", "1000.1"} {
			op := ExtractOperands(sample)
			assert.Equal(t, One, set.FormFunc(op))
		}

		for _, sample := range []string{"2", "3", "4", "22", "23", "24", "32", "33", "34", "42", "43", "44", "52", "53", "54", "62", "102", "1002", "0.2", "0.3", "0.4", "1.2", "1.3", "1.4", "2.2", "2.3", "2.4", "3.2", "3.3", "3.4", "4.2", "4.3", "4.4", "5.2", "10.2", "100.2", "1000.2"} {
			op := ExtractOperands(sample)
			assert.Equal(t, Few, set.FormFunc(op))
		}

		for _, sample := range []string{"0", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "100", "1000", "10000", "100000", "1000000", "0.0", "0.5", "0.6", "0.7", "0.8", "0.9", "1.0", "1.5", "1.6", "1.7", "1.8", "1.9", "2.0", "2.5", "2.6", "2.7", "10.0", "100.0", "1000.0", "10000.0", "100000.0", "1000000.0"} {
			op := ExtractOperands(sample)
			assert.Equal(t, Other, set.FormFunc(op))
		}

	}
}

func TestPrebuildGa(t *testing.T) {
	for _, lang := range []string{"ga"} {
		set, found := prebuildRuleSets[language.MustParse(lang)]
		require.True(t, found)

		for _, sample := range []string{"1", "1.0", "1.00", "1.000", "1.0000"} {
			op := ExtractOperands(sample)
			assert.Equal(t, One, set.FormFunc(op))
		}

		for _, sample := range []string{"2", "2.0", "2.00", "2.000", "2.0000"} {
			op := ExtractOperands(sample)
			assert.Equal(t, Two, set.FormFunc(op))
		}

		for _, sample := range []string{"3", "4", "5", "6", "3.0", "4.0", "5.0", "6.0", "3.00", "4.00", "5.00", "6.00", "3.000", "4.000", "5.000", "6.000", "3.0000", "4.0000", "5.0000", "6.0000"} {
			op := ExtractOperands(sample)
			assert.Equal(t, Few, set.FormFunc(op))
		}

		for _, sample := range []string{"7", "8", "9", "10", "7.0", "8.0", "9.0", "10.0", "7.00", "8.00", "9.00", "10.00", "7.000", "8.000", "9.000", "10.000", "7.0000", "8.0000", "9.0000", "10.0000"} {
			op := ExtractOperands(sample)
			assert.Equal(t, Many, set.FormFunc(op))
		}

		for _, sample := range []string{"0", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "100", "1000", "10000", "100000", "1000000", "0.0", "0.1", "0.2", "0.3", "0.4", "0.5", "0.6", "0.7", "0.8", "0.9", "1.1", "1.2", "1.3", "1.4", "1.5", "1.6", "10.1", "100.0", "1000.0", "10000.0", "100000.0", "1000000.0"} {
			op := ExtractOperands(sample)
			assert.Equal(t, Other, set.FormFunc(op))
		}

	}
}

func TestPrebuildHyKabFf(t *testing.T) {
	for _, lang := range []string{"hy", "kab", "ff"} {
		set, found := prebuildRuleSets[language.MustParse(lang)]
		require.True(t, found)

		for _, sample := range []string{"0", "1", "0.0", "0.1", "0.2", "0.3", "0.4", "0.5", "0.6", "0.7", "0.8", "0.9", "1.0", "1.1", "1.2", "1.3", "1.4", "1.5"} {
			op := ExtractOperands(sample)
			assert.Equal(t, One, set.FormFunc(op))
		}

		for _, sample := range []string{"2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "100", "1000", "10000", "100000", "1000000", "2.0", "2.1", "2.2", "2.3", "2.4", "2.5", "2.6", "2.7", "2.8", "2.9", "3.0", "3.1", "3.2", "3.3", "3.4", "3.5", "10.0", "100.0", "1000.0", "10000.0", "100000.0", "1000000.0"} {
			op := ExtractOperands(sample)
			assert.Equal(t, Other, set.FormFunc(op))
		}

	}
}

func TestPrebuildCy(t *testing.T) {
	for _, lang := range []string{"cy"} {
		set, found := prebuildRuleSets[language.MustParse(lang)]
		require.True(t, found)

		for _, sample := range []string{"0", "0.0", "0.00", "0.000", "0.0000"} {
			op := ExtractOperands(sample)
			assert.Equal(t, Zero, set.FormFunc(op))
		}

		for _, sample := range []string{"1", "1.0", "1.00", "1.000", "1.0000"} {
			op := ExtractOperands(sample)
			assert.Equal(t, One, set.FormFunc(op))
		}

		for _, sample := range []string{"2", "2.0", "2.00", "2.000", "2.0000"} {
			op := ExtractOperands(sample)
			assert.Equal(t, Two, set.FormFunc(op))
		}

		for _, sample := range []string{"3", "3.0", "3.00", "3.000", "3.0000"} {
			op := ExtractOperands(sample)
			assert.Equal(t, Few, set.FormFunc(op))
		}

		for _, sample := range []string{"6", "6.0", "6.00", "6.000", "6.0000"} {
			op := ExtractOperands(sample)
			assert.Equal(t, Many, set.FormFunc(op))
		}

		for _, sample := range []string{"4", "5", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "100", "1000", "10000", "100000", "1000000", "0.1", "0.2", "0.3", "0.4", "0.5", "0.6", "0.7", "0.8", "0.9", "1.1", "1.2", "1.3", "1.4", "1.5", "1.6", "1.7", "10.0", "100.0", "1000.0", "10000.0", "100000.0", "1000000.0"} {
			op := ExtractOperands(sample)
			assert.Equal(t, Other, set.FormFunc(op))
		}

	}
}

func TestPrebuildKsh(t *testing.T) {
	for _, lang := range []string{"ksh"} {
		set, found := prebuildRuleSets[language.MustParse(lang)]
		require.True(t, found)

		for _, sample := range []string{"0", "0.0", "0.00", "0.000", "0.0000"} {
			op := ExtractOperands(sample)
			assert.Equal(t, Zero, set.FormFunc(op))
		}

		for _, sample := range []string{"1", "1.0", "1.00", "1.000", "1.0000"} {
			op := ExtractOperands(sample)
			assert.Equal(t, One, set.FormFunc(op))
		}

		for _, sample := range []string{"2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "100", "1000", "10000", "100000", "1000000", "0.1", "0.2", "0.3", "0.4", "0.5", "0.6", "0.7", "0.8", "0.9", "1.1", "1.2", "1.3", "1.4", "1.5", "1.6", "1.7", "10.0", "100.0", "1000.0", "10000.0", "100000.0", "1000000.0"} {
			op := ExtractOperands(sample)
			assert.Equal(t, Other, set.FormFunc(op))
		}

	}
}
